andes/maintenance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from . import views

app_name = 'maintenance'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^workorder/(?P<workorder_number>[0-9]+)$', views.workorder, name="workorder"),
    url(r'^workorder/(?P<workorder_number>[0-9]+)/process', views.process_workorder, name="process_workorder"),
    url(r'^workdescription/(?P<suffix>[0-9]+)$', views.get_work_description, name="work_description"),
    url(r'^sparepartlist/(?P<suffix>[0-9]+)$', views.get_spare_part_list, name="spare_part_list"),
    url(r'^spareparttype/(?P<id>[0-9]+)$', views.get_spare_part_type, name="spare_part_type"),
    url(r'^inputlist/(?P<suffix>[0-9]+)$', views.get_input_list, name="input_list"),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

andes/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'', include('maintenance.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
]

andes/maintenance/views.py
# -*- coding: utf-8 -*-
import os
from datetime import datetime
from decimal import Decimal
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseForbidden, HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from PyPDF2 import PdfFileMerger, PdfFileReader
from wkhtmltopdf.utils import wkhtmltopdf, render_to_temporary_file
from wkhtmltopdf.views import PDFTemplateResponse

from .models import *

# Create your views here.
def index(request):
    template = 'maintenance/index.html'
    context = {}
    return render(request, template, context)

@login_required
def dashboard(request):
    template = 'maintenance/dashboard.html'
    workorder_list = WorkOrder.objects.all()
    context = {'workorder_list': workorder_list}
    return render(request, template, context)

@login_required
def workorder(request, workorder_number):
    try:
        workorder = WorkOrder.objects.get(pk=workorder_number)
        if workorder.is_closed:
            return HttpResponseForbidden("This WorkOrder is already closed")
    except WorkOrder.DoesNotExist:
        return Http404("This WorkOrder does not exist")

    context = {}
    context['workorder'] = workorder
    context['airport'] = Airport.objects.get(pk=Inventory.objects.filter(machine_number=workorder.machine_number.machine_number).latest('up_date').airport)
    context['inputs'] = Input.objects.all()
    context['spare_parts'] = SparePart.objects.all()
    context['workorder_work_description_list'] = WorkOrderWorkDescription.objects.filter(order_number=workorder.order_number)

    machine_instruction_list = MachineInstruction.objects.filter(machine_number=workorder.machine_number, level=workorder.level)
    context['last_instruction_list'] = machine_instruction_list.filter(instruction_type="Last")
    machine_instruction_list = machine_instruction_list.exclude(instruction_type="Last")

    if workorder.work_type.name == 'Preventivo':
        context['machine_spare_part_list'] = MachineSparePart.objects.filter(machine_number=workorder.machine_number, level=workorder.level)
        context['machine_input_list'] = MachineInput.objects.filter(machine_number=workorder.machine_number, level=workorder.level)

        context['first_instruction_list'] = machine_instruction_list.filter(instruction_type="First")
        machine_instruction_list = machine_instruction_list.exclude(instruction_type="First")
        context['machine_instruction_list'] = machine_instruction_list

        instruction_types = set()
        for i in machine_instruction_list:
            instruction_types.add(i.instruction_type.name)
        context['instruction_types'] = list(instruction_types)

        machine_lubrication_chart_list = MachineLubricationChart.objects.filter(machine_number=workorder.machine_number, level=workorder.level)
        context['machine_lubrication_chart_list'] = machine_lubrication_chart_list
        lubrication_chart_descriptions = []
        for i in machine_lubrication_chart_list:
            for j in LubricationChartDescription.objects.filter(lubrication_chart=i.id):
                lubrication_chart_descriptions.append((j.number, j.description))
        context['lubrication_chart_descriptions'] = sorted(lubrication_chart_descriptions)

        context['today'] = datetime.today()

    template = 'maintenance/workorder.html'

    return render(request, template, context)

@login_required
def process_workorder(request, workorder_number):
    try:
        workorder = WorkOrder.objects.get(pk=workorder_number)
        if workorder.is_closed:
            return HttpResponseForbidden("This WorkOrder is already closed")
    except WorkOrder.DoesNotExist:
        return Http404("This WorkOrder does not exist")

    context = {}
    context['workorder'] = workorder
    context['airport_code'] = (Airport.objects.get(pk=Inventory.objects.filter(machine_number=workorder.machine_number.machine_number).latest('up_date').airport)).code
    context['workorder_work_description_list'] = WorkOrderWorkDescription.objects.filter(order_number=workorder.order_number)
    form = request.POST

    out = map(int, form['output_date'].split("-") + form['output_time'].split(":"))
    out_datetime = datetime(out[0], out[1], out[2], out[3], out[4])
    context['out_datetime'] = out_datetime

    sp_ids = dict((s,form[s]) for s in form.keys() if "spare_part_number" in s and form[s] != "")
    sp_prices = {}
    sp_numbers = {}
    sp_descriptions = {}
    sp_quantitys = dict((s,form[s]) for s in form.keys() if "spare_part_quantity" in s and form[s] != "")
    for key in sp_ids:
        item = SparePart.objects.get(pk=form[key])
        sp_prices[key]=SparePartHistoricPrice.objects.filter(pk=item.id).latest('date').price
        sp_numbers[key]="F:%s S:%s" % (item.factory_number, item.sage_number)
        sp_descriptions[key.replace("number", "description")]=item.spare_part_type

    sp_order_numbers = sorted(sp_numbers)
    sp_order_descriptions = sorted(sp_descriptions)
    sp_order_quantitys = sorted(sp_quantitys)
    sp_order_prices = sorted(sp_prices)

    spare_parts = []
    spare_part_prices = []
    total_costs = []
    if workorder.work_type.name == 'Preventivo':
        machine_spare_part_list = MachineSparePart.objects.filter(machine_number=workorder.machine_number, level=workorder.level)
        for machine_spare_part in machine_spare_part_list:
            msp_number = "F:%s S:%s" % (machine_spare_part.spare_part.factory_number, machine_spare_part.spare_part.sage_number)
            msp_description = machine_spare_part.spare_part.spare_part_type
            msp_quantity = machine_spare_part.quantity
            msp_price = SparePartHistoricPrice.objects.filter(spare_part=machine_spare_part.spare_part.id).latest('date').price
            msp_total_price = msp_price * Decimal(msp_quantity)
            spare_parts.append((msp_number, msp_description, msp_quantity))
            spare_part_prices.append(msp_price)
            total_costs.append(msp_total_price)

    for i in xrange(len(sp_ids)):
        sp_total_price = sp_prices[sp_order_prices[i]] * Decimal(sp_quantitys[sp_order_quantitys[i]])
        spare_parts.append((sp_numbers[sp_order_numbers[i]], sp_descriptions[sp_order_descriptions[i]], sp_quantitys[sp_order_quantitys[i]]))
        spare_part_prices.append(sp_prices[sp_order_prices[i]])
        total_costs.append(sp_total_price)

    is_sp_len_greater_than_0 = len(spare_parts) > 0
    is_sp_even = len(spare_parts)%2 == 1
    if is_sp_even:
        range_sp = [(spare_parts[i], spare_parts[i+1]) for i in xrange(0, len(spare_parts)-1, 2)]
        range_sp.append((spare_parts[len(spare_parts)-1], ("", "", "")))
    else:
        range_sp = [(spare_parts[i], spare_parts[i+1]) for i in xrange(0, len(spare_parts), 2)]

    context['spare_parts'] = {  'range': range_sp,
                                'validator': is_sp_len_greater_than_0,
                            }

    i_ids = dict((s,form[s]) for s in form.keys() if "input_description" in s and form[s] != "")
    i_types = {}
    i_quantitys = dict((s,form[s]) for s in form.keys() if "input_quantity" in s and form[s] != "")
    for key in i_ids:
        i_types[key]= Input.objects.get(pk=form[key]).input_type

    i_order_types = sorted(i_types)
    i_order_quantitys = sorted(i_quantitys)

    inputs = []
    if workorder.work_type.name == 'Preventivo':
        machine_input_list = MachineInput.objects.filter(machine_number=workorder.machine_number, level=workorder.level)
        for machine_input in machine_input_list:
            inputs.append((machine_input.input_number.input_type, machine_input.quantity))

    for i in xrange(len(i_ids)):
        inputs.append((i_types[i_order_types[i]], i_quantitys[i_order_quantitys[i]]))

    is_i_len_greater_than_0 = len(inputs)
    context['inputs'] = {   'range': inputs,
                            'validator': is_i_len_greater_than_0,
                        }

    machine_instruction_list = MachineInstruction.objects.filter(machine_number=workorder.machine_number, level=workorder.level)
    context['last_instruction_list'] = machine_instruction_list.filter(instruction_type="Last")
    machine_instruction_list = machine_instruction_list.exclude(instruction_type="Last")

    if workorder.work_type.name == 'Preventivo':
        context['machine_spare_part_list'] = MachineSparePart.objects.filter(machine_number=workorder.machine_number, level=workorder.level)
        context['machine_input_list'] = MachineInput.objects.filter(machine_number=workorder.machine_number, level=workorder.level)

        context['first_instruction_list'] = machine_instruction_list.filter(instruction_type="First")
        machine_instruction_list = machine_instruction_list.exclude(instruction_type="First")
        context['machine_instruction_list'] = machine_instruction_list

        instruction_types = set()
        for i in machine_instruction_list:
            instruction_types.add(i.instruction_type.name)
        context['instruction_types'] = list(instruction_types)

        machine_lubrication_chart_list = MachineLubricationChart.objects.filter(machine_number=workorder.machine_number, level=workorder.level)
        context['machine_lubrication_chart_list'] = machine_lubrication_chart_list
        lubrication_chart_descriptions = []
        for i in machine_lubrication_chart_list:
            for j in LubricationChartDescription.objects.filter(lubrication_chart=i.id):
                lubrication_chart_descriptions.append((j.number, j.description))
        context['lubrication_chart_descriptions'] = sorted(lubrication_chart_descriptions)

        context['today'] = datetime.today()

    workorder_template = 'maintenance/process_workorder.html'
    header_template = 'maintenance/guideline_header.html'
    footer_template = 'maintenance/guideline_footer.html'

andes/maintenance/templates/maintenance/confirm_workorder.html
<!DOCTYPE HTML5>

{% load static %}
{% load workorder_extras %}

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css" href="{% static 'maintenance/stylesheet.css' %}" />
	</head>
	<body>
		<form action="{% url 'maintenance:process_workorder' %}" method="post" accept-charset="utf-8">
			{% csrf_token %}
			<table class="wo-table">
				<colgroup>
					<col class="wo-col-1">
					<col class="wo-col-2">
					<col class="wo-col-3">
					<col class="wo-col-4">
					<col class="wo-col-5">
					<col class="wo-col-6">
				</colgroup>
				<tr>
					<td rowspan=2 class="blank"><img src="{% static 'maintenance/images/andes.png' %}" width=121 height=48></td>
					<td colspan="2" class="blank"><br></td>
					<td class="wo-bg"><b>N° Orden</b></td>
					<td colspan="2" class="center-left">{{ workorder.order_number }}</td>
				</tr>
				<tr>
					<td colspan="5" class="blank"><br></td>
				</tr>
				<tr>
					<th colspan="6" class="blank">Orden de Trabajo</td>
				</tr>
				<tr>
					<td colspan="6" class="blank"><br></td>
				</tr>
				<tr>
					<td class="wo-solid-top wo-solid-left wo-bg">Familia</td>
					<td class="wo-solid-top">{{ workorder.machine_number.family.name }}</td>
					<td class="blank wo-solid-top"><br></td>
					<td class="wo-solid-top wo-bg">Horómetro</td>
					<td class="wo-solid-top">{{ request.POST.hourmeter_to_date }}</td>
					<td class="blank wo-solid-top wo-solid-right"><br></td>
				</tr>
				<tr>
					<td class="wo-solid-left wo-bg">Modelo</td>
					<td>{{ workorder.machine_number.subfamily.name }}</td>
					<td colspan="4" class="blank wo-solid-right"><br></td>
				</tr>
				<tr>
					<td class="wo-solid-left wo-bg">N° Equipo</td>
					<td>{{ workorder.machine_number.machine_number }}</td>
					<td colspan="4" class="blank wo-solid-right"><br></td>
				</tr>
				<tr>
					<td class="wo-solid-left wo-bg">ATO</td>
					<td>{{ airport_code }}</td>
					<td colspan="4" class="blank wo-solid-right"><br></td>
				</tr>
				<tr>
					<td colspan="6" class="blank wo-solid-left wo-solid-right"><br></td>
				</tr>
				<tr>
					<td rowspan="2" class="wo-solid-left wo-bg">Tipo de trabajo<br>(Marcar con una X)</td>
					<td class="wo-bg">Preventivo</td>
					<td class="center">
							{% if workorder.work_type.name == "Preventivo" %}
							<b>X</b>
							{% endif %}
					</td>
					<td class="blank"><br></td>
					<td class="wo-bg">Fecha</td>
					<td class="wo-solid-right wo-bg">Hora</td>
				</tr>
				<tr>
					<td class="wo-bg">Correctivo</td>
					<td class="center">
							{% if workorder.work_type.name == "Correctivo" %}
							<b>X</b>
							{% endif %}
					</td>
					<td class="wo-bg">Ingreso</td>
					<td>{{ workorder.in_datetime|date:"d/m/Y"}}</td>
					<td class="wo-solid-right">{{ workorder.in_datetime|date:"H:i" }}</td>
				</tr>
				<tr>
					<td class="blank wo-solid-left"><br></td>
					<td class="wo-bg">Falla</td>
					<td class="center">
						{% if request.POST.is_falla %}
						<b>X</b>
						{% endif %}
					</td>
					<td class="wo-bg">Salida est</td>
					<td>{{ out_datetime|date:"d/m/Y" }}</td>
					<td class="wo-solid-right">{{ out_datetime|date:"H:i" }}</td>
				</tr>
				<tr>
					<td class="blank wo-solid-left"><br></td>
					<td class="wo-bg">Daños</td>
					<td class="center">
						{% if request.POST.is_dannos %}
						<b>X</b>
						{% endif %}
					</td>
					<td colspan="3" class="blank wo-solid-right"><br></td>
				</tr>
				<tr>
					<td class="blank wo-solid-bottom wo-solid-left"><br></td>
					<td class="wo-solid-bottom wo-bg">Modificacion</td>
					<td class="wo-solid-bottom center">
						{% if request.POST.is_modificacion %}
							<b>X</b>
						{% endif %}
					</td>
					<td colspan="3" class="blank wo-solid-right wo-solid-bottom"><br></td>
				</tr>
				<tr>
					<td colspan="6" class="blank"><br></td>
				</tr>
				<tr>
					<td colspan="6" class="blank"><b>Diagnóstico / Intervención.</b></td>
				</tr>
				<tr>
					<td colspan="6" class="wo-solid-top wo-solid-right wo-solid-left wo-bg">Descripción de trabajo / falla</td>
				</tr>
				{% if work_descriptions.validator %}
					{% for key in work_descriptions.order %}
					<tr>
						<td colspan="6" class="wo-solid-right wo-solid-left">{{ work_descriptions.entries|key:key }}</td>
					</tr>
					{% endfor %}
				{% else %}
				<tr>
					<td colspan="6" class="wo-solid-right wo-solid-left"><br></td>
				</tr>
				{% endif %}
				<tr>
					<td colspan="6" class="wo-solid-right wo-solid-left wo-bg">Trabajo desarrollado</td>
				</tr>
				<tr>
					<td colspan="6" class="wo-solid-right wo-solid-left">{{ request.POST.developed_work }}</td>
				</tr>
				<tr>
					<td colspan="6" class="wo-solid-right wo-solid-left wo-bg">Trabajo pendiente</td>
				</tr>
				{% if request.POST.pending_job %}
				<tr>
					<td colspan="6" class="wo-solid-right wo-solid-left wo-solid-bottom">{{ request.POST.pending_job }}</td>
				</tr>
				{% else %}
				<tr>
					<td colspan="6" class="wo-solid-right wo-solid-left wo-solid-bottom"><br></td>
				</tr>
				{% endif %}
				<tr>
					<td colspan="6" class="blank"><br></td>
				</tr>
				<tr>
					<td colspan="6" class="blank"><b>Repuestos Empleados.</b></td>
				</tr>
				<tr>
					<td class="wo-solid-top wo-solid-left wo-bg">N° Parte</td>
					<td class="wo-solid-top wo-bg">Descripción</td>
					<td class="wo-solid-top wo-double-right wo-bg">Cantidad</td>
					<td class="wo-solid-top wo-double-left wo-bg">N° Parte</td>
					<td class="wo-solid-top wo-bg">Descripción</td>
					<td class="wo-solid-top wo-solid-right wo-bg">Cantidad</td>
				</tr>
				{% if spare_parts.validator %}
					{% for x1,y1,z1,x2,y2,z2 in spare_parts.range %}
					<tr>
						<td class="wo-solid-left">{{ spare_parts.numbers|key:x1 }}</td>
						<td>{{ spare_parts.descriptions|key:y1 }}</td>
						<td class="wo-double-right">{{ spare_parts.quantitys|key:z1 }}</td>
						{% if x2 != "" and y2 != "" and z2 != "" %}
						<td class="wo-double-left">{{ spare_parts.numbers|key:x2 }}</td>
						<td>{{ spare_parts.descriptions|key:y2 }}</td>
						<td class="wo-solid-right">{{ spare_parts.quantitys|key:z2 }}</td>
						{% else %}
						<td class="wo-double-left"><br></td>
						<td><br></td>
						<td class="wo-solid-right"><br></td>
						{% endif %}
					</tr>
					{% endfor %}
				{% else %}
				<tr>
					<td class="wo-solid-left"><br></td>
					<td><br></td>
					<td class="wo-double-right"><br></td>
					<td class="wo-double-left"><br></td>
					<td><br></td>
					<td class="wo-solid-right"><br></td>
				</tr>
				{% endif %}
				<tr>
					<td colspan="6" class="blank wo-solid-top"><br></td>
				</tr>
				<tr>
					<td colspan="6" class="blank"><b>Lubricantes Empleados.</b></td>
				</tr>
				<tr>
					<td class="wo-solid-top wo-solid-left wo-bg">Descripción</td>
					<td class="wo-solid-top wo-solid-right wo-bg">Cantidad</td>
					<td colspan="4" class="blank"><br></td>
				</tr>
				{% if inputs.validator %}
					{% for x,y in inputs.range %}
					<tr>
						<td class="wo-solid-left">{{ inputs.types|key:x }}</td>
						<td class="wo-solid-right">{{ inputs.quantitys|key:y }}</td>
						<td colspan="4" class="blank"><br></td>
					</tr>
					{% endfor %}
				{% else %}
				<tr>
					<td class="wo-solid-left"><br></td>
					<td class="wo-solid-right"><br></td>
					<td colspan="4" class="blank"><br></td>
				</tr>
				{% endif %}
				<tr>
					<td colspan="2" class="blank wo-solid-top"><br></td>
					<td colspan="4" class="blank"><br></td>
				</tr>
				<tr>
					<td colspan="6" class="blank"><b>Control de Salida.</b></td>
				</tr>
				<tr>
					<td colspan="2" class="blank wo-solid-top wo-solid-left"><br></td>
					<td class="wo-solid-top wo-bg">Fecha salida</td>
					<td class="wo-solid-top">{{ request.POST.output_date }}</td>
					<td class="wo-solid-top wo-bg">Hora salida</td>
					<td class="wo-solid-top wo-solid-right">{{ request.POST.output_time }}</td>
				</tr>
				<tr>
					<td colspan="6" class="blank wo-solid-right wo-solid-left"><br></td>
				</tr>
				<tr>
					<td class="blank wo-solid-left">Nombre Mecánico</td>
					<td colspan="2" class="blank">{{ user.first_name }} {{ user.last_name }}</td>
					<td class="blank">Firma</td>
					<td colspan="2" class="blank wo-solid-right">_________________________</td>
				</tr>
				<tr>
					<td class="blank wo-solid-bottom wo-solid-left">Nombre Team Leader</td>
					<td colspan="2" class="blank wo-solid-bottom">Carlos Orellana / Esteban Morales</td>
					<td class="blank wo-solid-bottom">Firma</td>
					<td colspan="2" class="blank wo-solid-right wo-solid-bottom">_________________________</td>
				</tr>
				<tr>
					<td colspan="6" class="blank wo-solid-top"><br></td>
				</tr>
			</table>
			<input type="submit" value="Confirm order">
		</form>
		<script src="{% static 'maintenance/js/jquery-3.1.1.js' %}"></script>
	</body>
</html>

andes/maintenance/templates/maintenance/dashboard.html
<!DOCTYPE HTML>

{% load static %}

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css" href="{% static 'maintenance/stylesheet.css' %}" />
	</head>
	<body>
    <div class="dashboard">
      <div class="workorder-list">
        <table>
          <tr>
            <td>Machine Number</td>
            <td>Machine Family</td>
            <td>Input Date</td>
            <td>Work Type</td>
            <td><br></td>
          </tr>
          {% for workorder in workorder_list %}
						{% if workorder.is_closed == False %}
	          <tr>
	            <td>{{ workorder.machine_number.machine_number }}</td>
	            <td>{{ workorder.machine_number.family.name }}</td>
	            <td>{{ workorder.in_datetime }}</td>
	            <td>{{ workorder.work_type.name }}</td>
	            <td><a href="/workorder/{{ workorder.order_number }}">I want this!</a></td>
	          </tr>
						{% endif %}
          {% endfor %}
        </table>
      </div>
      <div class="logout">
        <a href="/logout">Logout</a>
      </div>
    </div>
	</body>
</html>

andes/maintenance/templates/maintenance/download.html
<!DOCTYPE HTML>

{% load static %}

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css" href="{% static 'maintenance/stylesheet.css' %}" />
	</head>
	<body>
    <div class="index">
      <h3>Gran trabajo. ahora descarga e imprime el documento para terminar.</h3>
      <p>Descárgalo <a href="/media/{{ pdf_url }}">aquí</a></p>
      <p><a href="/dashboard/">Volver</a></p>
    </div>
	</body>
</html>

andes/maintenance/templates/maintenance/exit_checklist.html
<!DOCTYPE HTML>

{% load static %}

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css" href="{% static 'maintenance/stylesheet.css' %}" />
	</head>
	<body>
    <div id="exit-checklist">
      <table class="gl-table">
        <tr>
          <th colspan="4" class="blank">Checklist de Salida</th>
        </tr>
        <tr>
          <td class="blank">Item</td>
          <td class="blank">Descripción</td>
          <td class="center">Ticket de mecánico</td>
          <td class="center">Ticket de Team Leader</td>
        </tr>
        {% for instruction in last_instruction_list %}
        <tr>
          <td class="blank">{{ forloop.counter }}</td>
          <td class="blank">{{ instruction.instruction_number.description }}</td>
          <th>X</th>
          <th>X</th>
        </tr>
        {% endfor %}
        <tr>
          <td colspan="4" class="blank"><br></td>
        </tr>
        <tr>
          <td colspan="4">Observación</td>
        </tr>
				<tr>
					<td colspan="4">{{ request.POST.final_observations }}</td>
				</tr>
      </table>
      <table class="gl-table">
        <colgroup>
          <col class="gl-exit-col-1">
          <col class="gl-exit-col-2">
          <col class="gl-exit-col-3">
          <col class="gl-exit-col-4">
          <col class="gl-exit-col-5">
        </colgroup>
        <tr>
          <td colspan="5" class="blank"><br></td>
        </tr>
        <tr>
          <td class="blank"><br></td>
          <td class="blank center">{{ user.first_name }} {{ user.last_name }}</td>
          <td class="blank"><br></td>
          <td class="blank"><br></td>
          <td class="blank"><br></td>
        </tr>
        <tr>
          <td class="blank"><br></td>
          <th class="blank gl-solid-top">Mecánico</th>
          <td class="blank"><br></td>
          <th class="blank gl-solid-top">Firma</th>
          <td class="blank"><br></td>
        </tr>
        <tr>
          <td class="blank"><br></td>
          <td class="blank center">{{ workorder.team_leader.first_name }} {{ workorder.team_leader.last_name }}</td>
          <td class="blank"><br></td>
          <td class="blank"><br></td>
          <td class="blank"><br></td>
        </tr>
        <tr>
          <td class="blank"><br></td>
          <th class="blank gl-solid-top">Team Leader</th>
          <td class="blank"><br></td>
          <th class="blank gl-solid-top">Firma</th>
          <td class="blank"><br></td>
        </tr>
      </table>
    </div>
  </body>
</html>

andes/maintenance/templates/maintenance/guideline_footer.html
<!DOCTYPE HTML>

{% load static %}

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'maintenance/stylesheet.css' %}" />
  </head>
  <footer id="gl-footer">
    Página <span id="gl-footer-page"></span> de <span id="gl-footer-topage"></span>
  </footer>
  <script src="{% static 'maintenance/js/jquery-3.1.1.js' %}"></script>
  <script src="{% static 'maintenance/js/footer.js' %}"></script>
</html>

andes/maintenance/templates/maintenance/guideline_header.html
<!DOCTYPE HTML>

{% load static %}

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'maintenance/stylesheet.css' %}" />
  </head>
  <header id="gl-header">
    <table class="gl-table">
      <tr>
        <td colspan="2"><br></td>
        <td><br></td>
      </tr>
      <tr>
        <th><img src="{% static 'maintenance/images/latam.png' %}" name="latam" width="160" height="49"/></th>
        <th>PAUTA DE MANTENIMIENTO PREVENTIVO</th>
        <th><img src="{% static 'maintenance/images/andes.png' %}" name="andes" width="145" height="46"/></th>
      </tr>
    </table>
  </header>
</html>

andes/maintenance/templates/maintenance/index.html
<!DOCTYPE HTML>

{% load static %}

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css" href="{% static 'maintenance/stylesheet.css' %}" />
	</head>
	<body>
    <div class="index">
      <h1>Bienvenidos a la página principal de esta aplicación</h1>
      <h3>Por ahora no hay nada aquí, pero puede ingresar siguiendo el link inferior</h3>
      <a href="login/">Login</a>
    </div>
	</body>
</html>